<a href="https://colab.research.google.com/github/Het3375/MACHINE-LEARNING-PROJECT/blob/main/BASIC_REG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [109]:
DATA=pd.read_csv('train.csv')
DATA.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [110]:
DATA.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [111]:
NEW_DATA=DATA.drop(['Alley','PoolQC','Fence','MiscFeature'],axis=1)

In [112]:
NEW_DATA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [113]:
NUM_VALUE=NEW_DATA.drop(['SaleCondition','SaleType','PavedDrive','GarageQual','GarageCond','GarageFinish','GarageType','FireplaceQu','Functional','KitchenQual','Electrical','CentralAir','HeatingQC','Heating','BsmtFinType2','BsmtFinType1','BsmtExposure','BsmtCond','BsmtQual','Foundation','ExterCond','ExterQual','MasVnrType','Exterior2nd','Exterior1st','RoofMatl','RoofStyle','HouseStyle','BldgType','Condition2','Condition1','Neighborhood','LandSlope','LotConfig','Utilities','LandContour','LotShape','Street','MSZoning'],axis=1)

In [114]:
CATE_GO=NEW_DATA[['SaleCondition','SaleType','PavedDrive','GarageQual','GarageCond','GarageFinish','GarageType','FireplaceQu','Functional','KitchenQual','Electrical','CentralAir','HeatingQC','Heating','BsmtFinType2','BsmtFinType1','BsmtExposure','BsmtCond','BsmtQual','Foundation','ExterCond','ExterQual','MasVnrType','Exterior2nd','Exterior1st','RoofMatl','RoofStyle','HouseStyle','BldgType','Condition2','Condition1','Neighborhood','LandSlope','LotConfig','Utilities','LandContour','LotShape','Street','MSZoning']].copy()

In [115]:
CATE_GO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   SaleCondition  1460 non-null   object
 1   SaleType       1460 non-null   object
 2   PavedDrive     1460 non-null   object
 3   GarageQual     1379 non-null   object
 4   GarageCond     1379 non-null   object
 5   GarageFinish   1379 non-null   object
 6   GarageType     1379 non-null   object
 7   FireplaceQu    770 non-null    object
 8   Functional     1460 non-null   object
 9   KitchenQual    1460 non-null   object
 10  Electrical     1459 non-null   object
 11  CentralAir     1460 non-null   object
 12  HeatingQC      1460 non-null   object
 13  Heating        1460 non-null   object
 14  BsmtFinType2   1422 non-null   object
 15  BsmtFinType1   1423 non-null   object
 16  BsmtExposure   1422 non-null   object
 17  BsmtCond       1423 non-null   object
 18  BsmtQual       1423 non-null

In [116]:
NEW_CAT=pd.get_dummies((CATE_GO))

In [117]:
FINAL_DATA=pd.concat([NEW_CAT,NUM_VALUE],axis=1)

In [118]:
FINAL_STAP=FINAL_DATA.drop('SalePrice',axis=1)

In [119]:
final_labels=FINAL_DATA['SalePrice'].copy()

In [120]:
corr_matrix=FINAL_DATA.corr()
corr_matrix['SalePrice'].sort_values(ascending=False)

SalePrice           1.000000
OverallQual         0.790982
GrLivArea           0.708624
GarageCars          0.640409
GarageArea          0.623431
                      ...   
MasVnrType_None    -0.374468
GarageFinish_Unf   -0.410608
BsmtQual_TA        -0.452394
KitchenQual_TA     -0.519298
ExterQual_TA       -0.589044
Name: SalePrice, Length: 277, dtype: float64

PIPELINE

In [121]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
pipe=Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('std_scaler',StandardScaler()),
])
FINAL_NUM_TR=pipe.fit_transform(FINAL_STAP)
FINAL_NUM_TR

array([[-0.27261576, -0.05241424, -0.09103457, ..., -0.08768781,
        -1.5991111 ,  0.13877749],
       [-0.27261576, -0.05241424, -0.09103457, ..., -0.08768781,
        -0.48911005, -0.61443862],
       [-0.27261576, -0.05241424, -0.09103457, ..., -0.08768781,
         0.99089135,  0.13877749],
       ...,
       [-0.27261576, -0.05241424, -0.09103457, ...,  4.95311151,
        -0.48911005,  1.64520971],
       [-0.27261576, -0.05241424, -0.09103457, ..., -0.08768781,
        -0.8591104 ,  1.64520971],
       [-0.27261576, -0.05241424, -0.09103457, ..., -0.08768781,
        -0.1191097 ,  0.13877749]])

# PREDICTION

In [122]:
from sklearn.ensemble import RandomForestRegressor
# from sklearn.linear_model import LinearRegression
# from sklearn.tree import DecisionTreeRegressor
# model=LinearRegression()
model=RandomForestRegressor()
# model=DecisionTreeRegressor()
model.fit(FINAL_NUM_TR,final_labels)

RandomForestRegressor()

In [123]:
some_data=FINAL_STAP.iloc[:5]

In [124]:
some_labels=final_labels.iloc[:5]

In [125]:
prepared_data=pipe.transform(some_data)

In [126]:
model.predict(prepared_data)

array([207650.  , 175538.  , 220723.78, 150069.2 , 265937.5 ])

In [127]:
list(some_labels)

[208500, 181500, 223500, 140000, 250000]

In [128]:
from sklearn.metrics import mean_squared_error
predicitons=model.predict(FINAL_NUM_TR)
mean_value=mean_squared_error(final_labels,predicitons)
rmse=np.sqrt(mean_value)

In [129]:
rmse

10798.243656260345

# Cross-Validation

In [130]:
from sklearn import linear_model
from sklearn.metrics import fbeta_score, make_scorer
from sklearn.model_selection import  cross_val_score
scores=cross_val_score(model,FINAL_NUM_TR,final_labels,scoring=make_scorer(mean_squared_error,greater_is_better=False))
                                       
rmse_scores=np.sqrt(-scores)

In [131]:
rmse_scores

array([25992.41817589, 32219.648618  , 30482.09258031, 24869.91548047,
       34225.84747186])

In [132]:
def print_scores(scores):
  print("Scores",scores)
  print("Mean",scores.mean())
  print("Standered deviations",scores.std())

In [141]:
print_scores(rmse_scores)

Scores [25992.41817589 32219.648618   30482.09258031 24869.91548047
 34225.84747186]
Mean 29557.98446530708
Standered deviations 3589.3907752900413
